# Generated by Django 5.0.7 on 2024-08-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iamge',
            new_name='image',
        ),
    ]
